name: Deploy SeriesIndex Plugin
run-name: ${{ gitea.actor }} is Deploying SeriesIndex Plugin 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: pi4
    steps:
      - run: echo "🍏🍏🍏 ${{ secrets.DEPLOY_PORT }} + 1"
      - name: Check out repository code
        uses: http://git.mangolovecarrot.net/actions/checkout@v3
      - name: Upload Files
        id: upload
        uses: https://github.com/Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASS }}
          localPath: './*.php'
          remotePath: './'
      - run: echo "🍏 This job's status is ${{ job.status }}."
