name: Deploy SeriesIndex Plugin
run-name: ${{ gitea.actor }} is Deploying SeriesIndex Plugin 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: pi4
    steps:
      - run: echo "🍏🍏🍏 ${{ secrets.DEPLOY_PORT }} + 1"
      - name: Check out repository code
        uses: http://git.mangolovecarrot.net/actions/checkout@v3
      - name: scp ssh pipelines
        uses: http://git.mangolovecarrot.net/actions/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          user: ${{ secrets.DEPLOY_USER }}
          pass: ${{ secrets.DEPLOY_PASS }}
          scp: |
            ./*.* => ${{ secrets.DEPLOY_DEST }}
          last_ssh: |
            cd ${{ secrets.DEPLOY_DEST }}
            ls -la
      - run: echo "🍏 This job's status is ${{ job.status }}."
