name: Deploy SeriesIndex Plugin
run-name: ${{ gitea.actor }} is Deploying SeriesIndex Plugin 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: pi4
    steps:
      - name: Check out repository code
        uses: http://git.mangolovecarrot.net/actions/checkout@v3
      - name: scp pipelines
        uses: http://git.mangolovecarrot.net/actions/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          user: ${{ secrets.DEPLOY_USER }}
          pass: ${{ secrets.DEPLOY_PASS }}
          scp: |
            './*.php' => /.
      - run: echo "🍏 This job's status is ${{ job.status }}."
